"""Second-draft figures: the engineering, and the results as pictures.

Same rule as `paper/figures.py`: nothing is hand-drawn or hand-numbered. The
engineering figures read the live tables (port_events, terminal_zones,
priority_watchlist, vf_rescue_log, vf_account_status, model_panel); the result
figures read the replay JSON in `paper/results/`. The script also writes
`paper/numbers2.tex`, the macros for every engineering number quoted in prose,
so that a number which is not generated cannot appear in the text.

Usage:
  uv run python -m paper.figures2            # all figures
  uv run python -m paper.figures2 --only coverage zones
"""

from __future__ import annotations

import argparse
import asyncio
import json
import re
from datetime import date, datetime, timedelta, timezone
from pathlib import Path

import asyncpg
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
from matplotlib.patches import Patch, Polygon as MplPolygon  # noqa: E402
from matplotlib.lines import Line2D  # noqa: E402

from config import settings  # noqa: E402
from paper.figures import ACCENT, BLUE, GREEN, GREY, INK, RED, _save  # noqa: E402

HERE = Path(__file__).parent
RESULTS = HERE / "results"
NUMBERS2 = HERE / "numbers2.tex"

REGIME_COLOUR = {"noaa": INK, "gfw": BLUE, "bbox": GREY, "mmsi_filter": ACCENT}
REGIME_LABEL = {
    "noaa": "NOAA (US terrestrial)",
    "gfw": "GFW (voyage arcs)",
    "bbox": "live, bbox",
    "mmsi_filter": "live, MMSI filter",
}
SIGNAL_LABEL = {
    "gas_in_transit_eu": "gas in transit, EU-bound",
    "gas_in_transit_unknown": "gas in transit, unresolved",
    "gas_loading_us": "US loading rate",
    "gas_discharging_eu": "EU discharge rate",
    "gas_ballast_to_us": "ballast returning to US",
    "laden_voyage_age_d": "laden voyage age",
    "load_queue_h": "US load-queue wait",
    "net_export_pressure": "net export pressure",
}
SIGNAL_ORDER = list(SIGNAL_LABEL)
NUMBERS: dict[str, str] = {}


def _num(name: str, value) -> None:
    """Register a prose macro. Integers get thousands separators."""
    if isinstance(value, int):
        NUMBERS[name] = f"{value:,}"
    else:
        NUMBERS[name] = str(value)


def _write_numbers() -> None:
    lines = ["% GENERATED by paper/figures2.py — do not edit by hand"]
    for k in sorted(NUMBERS):
        lines.append(f"\\newcommand{{\\{k}}}{{{NUMBERS[k]}}}")
    NUMBERS2.write_text("\n".join(lines) + "\n")
    print(f"  wrote numbers2.tex ({len(NUMBERS)} macros)")


# ----------------------------------------------------------------------
# Fig — coverage: port events per quarter by feed, and the feed spans
# ----------------------------------------------------------------------

COVERAGE_SQL = """
SELECT date_trunc('quarter', event_time)::date AS q, regime, count(*) AS n
FROM port_events
WHERE event_time >= DATE '2016-01-01'
GROUP BY 1, 2 ORDER BY 1, 2
"""


async def fig_coverage(pool: asyncpg.Pool) -> None:
    """Where the events come from, quarter by quarter, and where each feed ends.

    The coverage seam of the paper (Section 3.5) is visible here as the point
    at which the two tall backfill series stop and only the thin live series
    remains. Drawn so the reader can see it before being told about it.
    """
    async with pool.acquire() as conn:
        rows = await conn.fetch(COVERAGE_SQL)
    quarters = sorted({r["q"] for r in rows})
    regimes = ["noaa", "gfw", "bbox", "mmsi_filter"]
    counts = {rg: np.zeros(len(quarters)) for rg in regimes}
    idx = {q: i for i, q in enumerate(quarters)}
    for r in rows:
        if r["regime"] in counts:
            counts[r["regime"]][idx[r["q"]]] = r["n"]

    fig, (ax0, ax1) = plt.subplots(
        2, 1, figsize=(7.2, 4.2), sharex=True, height_ratios=[1, 3.2]
    )
    spans = [
        ("NOAA archive", date(2016, 1, 1), date(2025, 12, 31), INK),
        ("GFW events", date(2016, 1, 1), date(2026, 2, 21), BLUE),
        ("live bbox", date(2026, 4, 1), date(2026, 5, 30), GREY),
        ("live MMSI filter", date(2026, 5, 30), date(2026, 8, 10), ACCENT),
    ]
    for i, (lab, lo, hi, col) in enumerate(spans):
        ax0.barh(i, (hi - lo).days, left=lo, height=0.6, color=col)
    ax0.set_yticks(range(len(spans)), [s[0] for s in spans], fontsize=7)
    ax0.invert_yaxis()
    ax0.grid(False)
    ax0.set_ylabel("feed span", fontsize=8)

    bottom = np.zeros(len(quarters))
    for rg in regimes:
        ax1.bar(
            quarters, counts[rg], width=80, bottom=bottom,
            color=REGIME_COLOUR[rg], label=REGIME_LABEL[rg], align="edge",
        )
        bottom += counts[rg]
    ax1.axvline(date(2025, 12, 31), color=RED, lw=0.9, ls="--")
    ax1.text(
        date(2025, 10, 1), bottom.max() * 0.92, "coverage seam\n(primary sample ends)",
        fontsize=7, color=RED, ha="right",
    )
    ax1.set_ylabel("port events per quarter")
    ax1.legend(fontsize=7.5, loc="upper left")
    ax1.set_xlim(date(2016, 1, 1), date(2026, 10, 1))
    _save(fig, "fig6_coverage")
    _num("nEventsPerQuarterPeak", int(bottom.max()))


# ----------------------------------------------------------------------
# Fig — the geometry: one terminal's polygons and the events they emit
# ----------------------------------------------------------------------

ZONES_SQL = """
SELECT z.zone_type, z.sub_zone, ST_AsGeoJSON(z.geom) AS gj
FROM terminal_zones z WHERE z.terminal_id = $1
"""
ZONE_EVENTS_SQL = """
SELECT event_type, lat, lon FROM port_events
WHERE terminal_id = $1 AND lat IS NOT NULL AND lon IS NOT NULL
  AND event_type IN ('zone_entry','anchored','moored','departed')
ORDER BY random() LIMIT $2
"""
ZONE_COUNT_SQL = """
SELECT count(*) FROM port_events WHERE terminal_id = $1 AND lat IS NOT NULL
"""
TERMINAL_SQL = "SELECT terminal_id, terminal_name, zone FROM terminals"


def _rings(gj: str):
    g = json.loads(gj)
    polys = g["coordinates"] if g["type"] == "MultiPolygon" else [g["coordinates"]]
    for poly in polys:
        yield np.array(poly[0])  # exterior ring, [lon, lat]


async def fig_zones(pool: asyncpg.Pool, terminal_id: int = 1, sample: int = 3000) -> None:
    """The hand-drawn polygons at Sabine Pass with a sample of the events
    the state machine emitted inside them. The approach envelope is the
    outer polygon; anchorage and berth are nested inside it."""
    async with pool.acquire() as conn:
        zones = await conn.fetch(ZONES_SQL, terminal_id)
        events = await conn.fetch(ZONE_EVENTS_SQL, terminal_id, sample)
        n_all = await conn.fetchval(ZONE_COUNT_SQL, terminal_id)
        terms = {r["terminal_id"]: r["terminal_name"] for r in await conn.fetch(TERMINAL_SQL)}
        n_polys = await conn.fetchval("SELECT count(*) FROM terminal_zones")
        n_terms = await conn.fetchval("SELECT count(*) FROM terminals")
    _num("nZonePolygons", int(n_polys))
    _num("nTerminals", int(n_terms))
    _num("nZoneFigureEvents", int(n_all))
    _num("zoneFigureTerminal", terms.get(terminal_id, str(terminal_id)))

    style = {
        "approach": dict(facecolor="#eef1f6", edgecolor=GREY, lw=0.8, zorder=1),
        "anchorage": dict(facecolor="#dbe6f5", edgecolor=BLUE, lw=0.9, zorder=2, hatch="//"),
        "berth": dict(facecolor="#f3e4c4", edgecolor=ACCENT, lw=1.0, zorder=3),
    }
    fig, ax = plt.subplots(figsize=(4.6, 4.9))
    for z in sorted(zones, key=lambda r: {"approach": 0, "anchorage": 1, "berth": 2}[r["zone_type"]]):
        for ring in _rings(z["gj"]):
            ax.add_patch(MplPolygon(ring, closed=True, **style[z["zone_type"]]))
    ev_style = {
        "zone_entry": (GREY, "o", 6),
        "anchored": (BLUE, "s", 9),
        "moored": (INK, "D", 9),
        "departed": (RED, "^", 10),
    }
    for et, (col, mk, sz) in ev_style.items():
        pts = [(r["lon"], r["lat"]) for r in events if r["event_type"] == et]
        if pts:
            xy = np.array(pts)
            ax.scatter(xy[:, 0], xy[:, 1], s=sz, marker=mk, color=col, alpha=0.55,
                       linewidths=0, zorder=4, label=f"{et.replace('_', ' ')} (n={len(pts)})")
    xs = np.concatenate([np.array([r["lon"] for r in events]), *[rg[:, 0] for z in zones for rg in _rings(z["gj"])]])
    ys = np.concatenate([np.array([r["lat"] for r in events]), *[rg[:, 1] for z in zones for rg in _rings(z["gj"])]])
    pad = 0.02
    ax.set_xlim(xs.min() - pad, xs.max() + pad)
    ax.set_ylim(ys.min() - pad, ys.max() + pad)
    ax.set_aspect(1 / np.cos(np.deg2rad(float(ys.mean()))))
    ax.set_xlabel("longitude")
    ax.set_ylabel("latitude")
    handles = [Patch(**{k: v for k, v in style[t].items() if k in ("facecolor", "edgecolor", "hatch")}, label=t)
               for t in ("approach", "anchorage", "berth")]
    handles += ax.get_legend_handles_labels()[0]
    ax.legend(handles=handles, fontsize=7, loc="lower right")
    ax.set_title(f"{terms.get(terminal_id, terminal_id)}: zone polygons and a sample of {len(events):,} events",
                 fontsize=8.5, loc="left")
    _save(fig, "fig7_zones")


# ----------------------------------------------------------------------
# Fig — one carrier's year: the three pairings on a timeline
# ----------------------------------------------------------------------

VESSEL_SQL = """
SELECT event_time, event_type, zone, terminal_id, laden_flag
FROM port_events WHERE mmsi = $1 AND event_time >= $2 AND event_time < $3
ORDER BY event_time
"""


async def fig_vessel(pool: asyncpg.Pool, mmsi: int = 224451000, year: int = 2024) -> None:
    """A single carrier's calendar year as legs, visits and queues.

    Each row is a terminal. A thick bar is a berth visit (moored -> departed),
    a hatched bar the anchorage wait before it, and a diagonal line a voyage
    leg (departed -> next zone entry elsewhere). Laden legs run US -> Europe,
    ballast legs run back. This is what `legs.py`, `visits.py` and
    `queues.py` pair, drawn rather than described.
    """
    lo = datetime(year, 1, 1, tzinfo=timezone.utc)
    hi = datetime(year + 1, 1, 1, tzinfo=timezone.utc)
    async with pool.acquire() as conn:
        ev = await conn.fetch(VESSEL_SQL, mmsi, lo, hi)
        terms = {r["terminal_id"]: (r["terminal_name"], r["zone"]) for r in await conn.fetch(TERMINAL_SQL)}
    _num("vesselFigureMmsi", str(mmsi))
    _num("vesselFigureYear", str(year))
    _num("vesselFigureEvents", len(ev))

    tids = sorted({r["terminal_id"] for r in ev if r["terminal_id"] is not None},
                  key=lambda t: (0 if terms[t][1].startswith("us") else 1, terms[t][0]))
    row = {t: i for i, t in enumerate(tids)}

    visits, queues, legs = [], [], []
    open_moored, open_anch, last_dep = {}, {}, None
    n_legs_laden = n_legs_ballast = 0
    for r in ev:
        t, et, ts = r["terminal_id"], r["event_type"], r["event_time"]
        if et == "anchorage_entry" and t not in open_anch:
            open_anch[t] = ts
        elif et == "moored":
            open_moored[t] = ts
            if t in open_anch:
                queues.append((t, open_anch.pop(t), ts))
        elif et == "departed":
            if t in open_moored:
                visits.append((t, open_moored.pop(t), ts, bool(r["laden_flag"])))
            open_anch.pop(t, None)
            last_dep = (t, ts, bool(r["laden_flag"]))
        elif et == "zone_entry" and last_dep is not None and last_dep[0] != t:
            legs.append((last_dep[0], last_dep[1], t, ts, last_dep[2]))
            if last_dep[2]:
                n_legs_laden += 1
            else:
                n_legs_ballast += 1
            last_dep = None
    _num("vesselFigureLadenLegs", n_legs_laden)
    _num("vesselFigureBallastLegs", n_legs_ballast)
    _num("vesselFigureVisits", len(visits))

    fig, ax = plt.subplots(figsize=(7.2, 3.6))
    for t, a, b in queues:
        ax.barh(row[t], (b - a).total_seconds() / 86400, left=a, height=0.55,
                color="none", edgecolor=BLUE, hatch="////", lw=0.6, zorder=2)
    for t, a, b, laden in visits:
        ax.barh(row[t], max((b - a).total_seconds() / 86400, 0.6), left=a, height=0.55,
                color=ACCENT if laden else INK, zorder=3)
    for t0, a, t1, b, laden in legs:
        ax.plot([a, b], [row[t0], row[t1]], color=ACCENT if laden else GREY,
                lw=1.1 if laden else 0.9, ls="-" if laden else "--", zorder=1)
    ax.set_yticks(range(len(tids)), [f"{terms[t][0]}" for t in tids], fontsize=7.5)
    ax.invert_yaxis()
    ax.axhline(sum(1 for t in tids if terms[t][1].startswith("us")) - 0.5, color=GREY, lw=0.6)
    ax.set_xlim(lo, hi)
    handles = [
        Patch(color=ACCENT, label="berth visit (leaves laden)"),
        Patch(color=INK, label="berth visit (leaves ballast)"),
        Patch(facecolor="none", edgecolor=BLUE, hatch="////", label="anchorage queue"),
        Line2D([0], [0], color=ACCENT, lw=1.1, label="laden leg"),
        Line2D([0], [0], color=GREY, lw=0.9, ls="--", label="ballast leg"),
    ]
    ax.legend(handles=handles, fontsize=7, loc="upper center", ncol=5, bbox_to_anchor=(0.5, -0.12))
    ax.set_title(f"MMSI {mmsi}, {year}: {len(visits)} visits, {n_legs_laden} laden and {n_legs_ballast} ballast legs",
                 fontsize=8.5, loc="left")
    _save(fig, "fig8_vessel_year")


# ----------------------------------------------------------------------
# Fig — the watchlist: who holds a subscription slot
# ----------------------------------------------------------------------

WATCHLIST_SQL = """
SELECT tier, coalesce(slot_kind, 'none') AS kind, count(*) AS n
FROM priority_watchlist GROUP BY 1, 2 ORDER BY 1, 2
"""


async def fig_watchlist(pool: asyncpg.Pool) -> None:
    """Slot allocation by tier: the scarce subscription slots and who has one."""
    async with pool.acquire() as conn:
        rows = await conn.fetch(WATCHLIST_SQL)
    tiers = sorted({r["tier"] for r in rows})
    kinds = ["pinned", "persistent", "scan", "none"]
    colour = {"pinned": RED, "persistent": INK, "scan": ACCENT, "none": "#e3e8f0"}
    label = {"pinned": "pinned (open leg / in port)", "persistent": "persistent slot",
             "scan": "scan rotation", "none": "no slot"}
    m = {(r["tier"], r["kind"]): r["n"] for r in rows}
    total = sum(r["n"] for r in rows)
    slotted = sum(r["n"] for r in rows if r["kind"] != "none")
    _num("nWatchlistVessels", int(total))
    _num("nWatchlistSlotted", int(slotted))
    for k in kinds:
        _num("nSlots" + k.capitalize(), int(sum(r["n"] for r in rows if r["kind"] == k)))

    fig, ax = plt.subplots(figsize=(4.4, 2.5))
    left = np.zeros(len(tiers))
    for k in kinds:
        vals = np.array([m.get((t, k), 0) for t in tiers], float)
        ax.barh(tiers, vals, left=left, color=colour[k], label=label[k], height=0.62,
                edgecolor="white", lw=0.4)
        left += vals
    for i, t in enumerate(tiers):
        ax.text(left[i] + 4, t, f"{int(left[i])}", va="center", fontsize=7.5, color=INK)
    ax.set_yticks(tiers, [f"tier {t}" for t in tiers])
    ax.invert_yaxis()
    ax.set_xlabel("vessels")
    ax.set_xscale("symlog", linthresh=100)
    ax.legend(fontsize=7, loc="lower right")
    ax.set_title(f"{total} LNG carriers and FSRUs ranked; {slotted} hold a subscription slot",
                 fontsize=8.5, loc="left")
    _save(fig, "fig9_watchlist")


# ----------------------------------------------------------------------
# Fig — the rescue backstop: outcomes by class, and the credit glide
# ----------------------------------------------------------------------

RESCUE_SQL = """
SELECT rescue_class, result, count(*) AS n, sum(credits) AS credits
FROM vf_rescue_log GROUP BY 1, 2
"""
BALANCE_SQL = """
SELECT checked_at, credits, expiration_date FROM vf_account_status ORDER BY checked_at
"""


async def fig_rescue(pool: asyncpg.Pool) -> None:
    """Left: what each rescue class returned. Right: the account balance against
    the glide line that the daily cap is derived from."""
    async with pool.acquire() as conn:
        rows = await conn.fetch(RESCUE_SQL)
        bal = await conn.fetch(BALANCE_SQL)
    classes = sorted({r["rescue_class"] for r in rows},
                     key=lambda c: -sum(r["n"] for r in rows if r["rescue_class"] == c))
    results = ["rescued", "no_position", "skipped_budget", "other"]
    colour = {"rescued": GREEN, "no_position": GREY, "skipped_budget": "#e3e8f0", "other": RED}

    def bucket(res: str) -> str:
        return res if res in results else "other"

    m: dict[tuple[str, str], int] = {}
    for r in rows:
        m[(r["rescue_class"], bucket(r["result"]))] = m.get((r["rescue_class"], bucket(r["result"])), 0) + r["n"]
    credits_total = int(sum(r["credits"] or 0 for r in rows))
    rescued_total = int(sum(r["n"] for r in rows if r["result"] == "rescued"))
    skipped_total = int(sum(r["n"] for r in rows if r["result"] == "skipped_budget"))
    _num("nRescueLookups", int(sum(r["n"] for r in rows if r["result"] not in ("skipped_budget", "dry_run"))))
    _num("nRescued", rescued_total)
    _num("nRescueSkipped", skipped_total)
    _num("nRescueCredits", credits_total)

    fig, (ax0, ax1) = plt.subplots(1, 2, figsize=(7.2, 3.2), width_ratios=[1.25, 1])
    left = np.zeros(len(classes))
    for res in results:
        vals = np.array([m.get((c, res), 0) for c in classes], float)
        ax0.barh(range(len(classes)), vals, left=left, color=colour[res],
                 label=res.replace("_", " "), height=0.65, edgecolor="white", lw=0.4)
        left += vals
    ax0.set_yticks(range(len(classes)), [c.replace("_", " ") for c in classes], fontsize=7)
    ax0.invert_yaxis()
    ax0.set_xscale("symlog", linthresh=50)
    ax0.set_xlabel("lookups (symlog)")
    ax0.legend(fontsize=6.5, loc="lower right")

    if bal:
        ts = [r["checked_at"] for r in bal]
        cr = np.array([r["credits"] for r in bal], float)
        exp = bal[-1]["expiration_date"]
        ax1.plot(ts, cr, color=INK, lw=1.2, label="account balance")
        if exp is not None:
            ax1.plot([ts[0], exp], [cr[0], 0], color=ACCENT, lw=1.0, ls="--",
                     label="glide line to expiry")
            ax1.set_xlim(ts[0] - timedelta(days=5), exp + timedelta(days=10))
            _num("vfExpiry", exp.date().isoformat())
        _num("vfCreditsStart", int(cr[0]))
        _num("vfCreditsNow", int(cr[-1]))
        _num("vfCreditsAsOf", ts[-1].date().isoformat())
        ax1.set_ylim(0, cr.max() * 1.08)
        ax1.set_ylabel("VesselFinder credits")
        ax1.legend(fontsize=7, loc="upper right")
        for lab in ax1.get_xticklabels():
            lab.set_rotation(30)
            lab.set_ha("right")
    _save(fig, "fig10_rescue")


# ----------------------------------------------------------------------
# Fig — the Part A target series with the two naive nulls drawn on it
# ----------------------------------------------------------------------

LOADINGS_SQL = """
SELECT date_trunc('week', event_time)::date AS w, count(*) AS n
FROM port_events
WHERE event_type = 'departed' AND laden_flag AND regime = 'noaa'
  AND zone IN ('usgulf', 'usatlantic')
GROUP BY 1 ORDER BY 1
"""


async def fig_loadings(pool: asyncpg.Pool) -> None:
    """Weekly US laden departures on the NOAA feed, with the trailing
    four-week mean (the climatology null) and the EWMA at A4's fitted alpha."""
    async with pool.acquire() as conn:
        rows = await conn.fetch(LOADINGS_SQL)
    a4 = json.loads((RESULTS / "a4.json").read_text())
    alpha = float(a4["alpha_mean"])
    weeks = [r["w"] for r in rows]
    lo, hi = weeks[0], weeks[-1]
    grid = [lo + timedelta(days=7 * i) for i in range((hi - lo).days // 7 + 1)]
    have = {r["w"]: r["n"] for r in rows}
    y = np.array([have.get(w, 0) for w in grid], float)
    trail4 = np.array([y[max(0, i - 4):i].mean() if i >= 1 else np.nan for i in range(len(y))])
    ewma = np.full_like(y, np.nan)
    s = y[0]
    for i in range(1, len(y)):
        ewma[i] = s
        s = alpha * y[i] + (1 - alpha) * s
    _num("loadingsWeeklyPeak", int(y.max()))
    _num("loadingsWeeklyMeanTwentyFive", f"{y[[g.year == 2025 for g in grid]].mean():.1f}")
    _num("aFourAlphaFig", f"{alpha:.3f}")

    fig, ax = plt.subplots(figsize=(7.2, 3.0))
    ax.bar(grid, y, width=6, color="#d5dbe6", label="weekly laden departures (NOAA)")
    ax.plot(grid, trail4, color=INK, lw=1.0, label="trailing 4-week mean (climatology null)")
    ax.plot(grid, ewma, color=ACCENT, lw=1.0, label=f"EWMA, $\\alpha$ = {alpha:.3f} (A4 steady state)")
    ax.annotate("Freeport outage\n(June 2022)", xy=(date(2022, 6, 8), 22), xytext=(date(2020, 9, 1), 33),
                fontsize=7, arrowprops=dict(arrowstyle="-", color=GREY, lw=0.7))
    ax.annotate("COVID cargo\ncancellations", xy=(date(2020, 7, 6), 3), xytext=(date(2018, 10, 1), 20),
                fontsize=7, arrowprops=dict(arrowstyle="-", color=GREY, lw=0.7))
    ax.set_ylabel("cargoes per week")
    ax.set_xlim(date(2016, 1, 1), date(2026, 1, 1))
    ax.legend(fontsize=7, loc="upper left")
    _save(fig, "fig11_loadings")


# ----------------------------------------------------------------------
# Result figures from the replay JSON
# ----------------------------------------------------------------------


def fig_parta() -> None:
    """One-week MAE for each Part A model against its two nulls."""
    a1 = json.loads((RESULTS / "a1.json").read_text())["scorecards"]["W1"]
    a2 = json.loads((RESULTS / "a2.json").read_text())["scorecards"]["W1"]
    a4 = json.loads((RESULTS / "a4.json").read_text())["scorecards"]["W1"]
    rows = [
        ("A1 arrival\nclimatology\n(EU arrivals)", a1["a1_mae"], a1["persist_mae"], a1["clim_mae"]),
        ("A2 negative-\nbinomial GLM\n(US loadings)", a2["mae"], a2["persist_mae"], a2["clim_mae"]),
        ("A4 Kalman\nlocal level\n(US loadings)", a4["mae"], a4["persist_mae"], a4["clim_mae"]),
    ]
    fig, ax = plt.subplots(figsize=(4.4, 3.0))
    x = np.arange(len(rows))
    w = 0.26
    ax.bar(x - w, [r[1] for r in rows], w, color=INK, label="model")
    ax.bar(x, [r[2] for r in rows], w, color=GREY, label="persistence null")
    ax.bar(x + w, [r[3] for r in rows], w, color=ACCENT, label="4-week climatology null")
    for i, r in enumerate(rows):
        skill = (r[1] - r[3]) / r[3] * 100
        ax.text(i - w, r[1] + 0.08, f"{skill:+.1f}%\nvs clim.", ha="center", fontsize=7, color=INK)
    ax.set_xticks(x, [r[0] for r in rows], fontsize=7.5)
    ax.set_ylabel("one-week MAE (cargoes)")
    ax.set_ylim(0, max(r[1] for r in rows) * 1.3)
    ax.legend(fontsize=7, loc="upper right")
    _save(fig, "fig12_parta")


def fig_h1() -> None:
    """The withdrawn horizon test: the conditional truth empties past the voyage
    tail while the unconditional nulls keep predicting the full weekly rate."""
    sc = json.loads((RESULTS / "a1_h1.json").read_text())["scorecards"]
    ws = ["W1", "W2", "W3", "W4"]
    truth = [sc[w]["mean_truth"] for w in ws]
    a1 = [sc[w]["a1_mae"] for w in ws]
    pers = [sc[w]["persist_mae"] for w in ws]
    clim = [sc[w]["clim_mae"] for w in ws]
    fig, ax = plt.subplots(figsize=(4.4, 2.9))
    x = np.arange(4)
    ax.bar(x, truth, 0.5, color="#d5dbe6", label="mean conditional truth (arrivals/week)")
    ax.plot(x, a1, marker="o", color=INK, lw=1.2, label="A1 MAE")
    ax.plot(x, pers, marker="s", color=GREY, lw=1.0, label="persistence MAE")
    ax.plot(x, clim, marker="^", color=ACCENT, lw=1.0, label="climatology MAE")
    ax.axvspan(1.5, 3.5, color=RED, alpha=0.06)
    ax.text(2.5, max(pers) * 0.98, "not comparable:\ntarget has emptied", ha="center", fontsize=7, color=RED)
    ax.set_xticks(x, ["week 1", "week 2", "week 3", "week 4"])
    ax.set_ylabel("cargoes")
    ax.legend(fontsize=7, loc="upper left")
    _save(fig, "fig13_h1")


def fig_outage() -> None:
    """Recall against false alarms for the three outage detectors."""
    a5 = json.loads((RESULTS / "a5.json").read_text())["headline"]
    names = {"bocpd": "BOCPD", "n1_absolute": "N1 absolute 14 d",
             "n2_rate_relative": "N2 rate-relative"}
    fig, ax = plt.subplots(figsize=(4.4, 3.0))
    for key, lab in names.items():
        d = a5[key]
        col = INK if key == "n2_rate_relative" else GREY
        ax.scatter(d["false_alarms_per_terminal_yr"], d["recall"], s=60 + 10 * d["median_delay_d"],
                   color=col, zorder=3)
        ax.annotate(f"{lab}\n{d['median_delay_d']} d median, {d['n_hit']}/{d['n_outages']}",
                    (d["false_alarms_per_terminal_yr"], d["recall"]), xytext=(7, -3),
                    textcoords="offset points", fontsize=6.5)
    ax.set_xscale("log")
    ax.set_xlim(0.08, 8)
    ax.set_ylim(0, 1.0)
    ax.set_xlabel("false alarms per terminal-year (log)")
    ax.set_ylabel("recall on 16 labelled outages")
    _save(fig, "fig14_outage")


def fig_ladder_year() -> None:
    """Per-year MAE of the model ladder on the primary sample, both horizons."""
    b0 = json.loads((RESULTS / "b0_coverage.json").read_text())["horizons"]
    fig, axes = plt.subplots(1, 2, figsize=(7.2, 2.9), sharey=False)
    colour = {"M0": INK, "M1": GREY, "M2": ACCENT}
    for ax, h in zip(axes, ("1", "4")):
        py = b0[h]["per_year_mae"]
        years = sorted(py["M0"])
        x = np.arange(len(years))
        for j, m in enumerate(("M0", "M1", "M2")):
            ax.bar(x + (j - 1) * 0.27, [py[m][y] for y in years], 0.27, color=colour[m], label=m)
        ax.set_xticks(x, years, fontsize=7.5)
        ax.set_title(f"h = {h} week{'s' if h != '1' else ''}", fontsize=8.5, loc="left")
        ax.set_ylabel("MAE ($/MMBtu)")
    axes[0].legend(fontsize=7, loc="upper left")
    _save(fig, "fig15_ladder_year")


def fig_year_signs() -> None:
    """Sign of each signal's partial effect in each year, against its prior."""
    b0 = json.loads((RESULTS / "b0_coverage.json").read_text())["horizons"]
    years = ["2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025"]
    fig, axes = plt.subplots(1, 2, figsize=(7.2, 3.1), sharey=True)
    for ax, h in zip(axes, ("1", "4")):
        fwl = b0[h]["fwl"]
        grid = np.zeros((len(SIGNAL_ORDER), len(years)))
        for i, s in enumerate(SIGNAL_ORDER):
            prior = fwl[s]["expected_sign"]
            for j, y in enumerate(years):
                sign = fwl[s]["year_signs"].get(y, 0)
                grid[i, j] = 0.5 if prior == 0 else (1 if sign == prior else -1)
        cmap = matplotlib.colors.ListedColormap([RED, "#e3e8f0", "#cfd7e3", GREEN])
        norm = matplotlib.colors.BoundaryNorm([-1.5, -0.5, 0.25, 0.75, 1.5], cmap.N)
        ax.imshow(grid, cmap=cmap, norm=norm, aspect="auto")
        for i, s in enumerate(SIGNAL_ORDER):
            for j, y in enumerate(years):
                sg = fwl[s]["year_signs"].get(y, 0)
                ax.text(j, i, "+" if sg > 0 else "−", ha="center", va="center", fontsize=8,
                        color="white" if grid[i, j] in (1, -1) else INK)
            ax.text(len(years) - 0.4, i, f"{fwl[s]['year_consistency'] * 100:.0f}%  t={fwl[s]['t_stat']:+.2f}",
                    va="center", fontsize=6.5, color=INK)
        ax.set_xticks(range(len(years)), ["'" + y[2:] for y in years], fontsize=7)
        ax.set_xlim(-0.5, len(years) + 2.4)
        ax.set_title(f"h = {h} week{'s' if h != '1' else ''}", fontsize=8.5, loc="left")
        ax.grid(False)
    axes[0].set_yticks(range(len(SIGNAL_ORDER)), [SIGNAL_LABEL[s] for s in SIGNAL_ORDER], fontsize=7.5)
    handles = [Patch(color=GREEN, label="sign matches prior"), Patch(color=RED, label="sign opposes prior"),
               Patch(color="#cfd7e3", label="no prior")]
    fig.legend(handles=handles, fontsize=7, loc="lower center", ncol=3, bbox_to_anchor=(0.5, -0.04))
    _save(fig, "fig16_year_signs")


def fig_mechanisms() -> None:
    """The three mechanism tests: t on discovery against the Bonferroni bar, and
    whether the holdout coefficient carries the same sign."""
    mech = json.loads((RESULTS / "mechanisms_coverage.json").read_text())
    bar = mech["bonferroni_t"]
    labels = {"eu_share": "H2: EU share of at-sea stock", "transit_x_storage": "H3: transit × EU storage",
              "transit_in_tight": "H4: transit, tight regime", "transit_in_loose": "H4: transit, loose regime"}
    res = mech["results"]
    fig, ax = plt.subplots(figsize=(6.6, 2.8))
    for i, r in enumerate(res):
        ax.scatter(r["t_stat"], i, s=34, color=INK, zorder=3)
        prior = "+" if r["expected_sign"] > 0 else "−"
        hb = r["holdout_beta"]
        if hb is None:
            hold = "no holdout (split)"
        else:
            same = (hb > 0) == (r["beta"] > 0)
            hold = "holdout sign " + ("replicates" if same else "flips")
        got = "+" if r["beta"] > 0 else "−"
        ax.text(3.05, i, f"prior {prior}, got {got}; {hold}; year cons. {r['year_consistency'] * 100:.0f}%",
                va="center", fontsize=7, color=INK)
    for b, ls in ((bar, "--"), (1.96, ":")):
        ax.axvline(b, color=RED, lw=0.8, ls=ls)
        ax.axvline(-b, color=RED, lw=0.8, ls=ls)
    ax.axvline(0, color=GREY, lw=0.8)
    ax.text(bar + 0.05, -0.75, f"Bonferroni |t| = {bar}", fontsize=7, color=RED)
    ax.set_yticks(range(len(res)), [labels[r["name"]] for r in res], fontsize=7.5)
    ax.invert_yaxis()
    ax.set_xlim(-3, 6.5)
    ax.set_xlabel("Newey–West HAC $t$ on the discovery sample, $h$ = 4")
    ax.grid(False)
    _save(fig, "fig17_mechanisms")


SIGNALS_SQL = """
SELECT bucket_date, feature, value FROM model_panel
WHERE feature = ANY($1::text[]) AND bucket_date >= DATE '2018-01-01' AND bucket_date <= $2
ORDER BY bucket_date
"""


async def fig_signals(pool: asyncpg.Pool, end: date = date(2025, 12, 31)) -> None:
    """The eight pre-registered signals, daily, on the primary sample."""
    async with pool.acquire() as conn:
        rows = await conn.fetch(SIGNALS_SQL, SIGNAL_ORDER, end)
    series: dict[str, tuple[list, list]] = {s: ([], []) for s in SIGNAL_ORDER}
    for r in rows:
        if r["value"] is not None:
            series[r["feature"]][0].append(r["bucket_date"])
            series[r["feature"]][1].append(float(r["value"]))
    units = {
        "gas_in_transit_eu": ("M m³", 1e6), "gas_in_transit_unknown": ("M m³", 1e6),
        "gas_loading_us": ("M m³/day", 1e6), "gas_discharging_eu": ("M m³/day", 1e6),
        "gas_ballast_to_us": ("M m³", 1e6), "laden_voyage_age_d": ("days", 1),
        "load_queue_h": ("hours", 1), "net_export_pressure": ("z-score", 1),
    }
    fig, axes = plt.subplots(4, 2, figsize=(7.2, 6.0), sharex=True)
    for ax, s in zip(axes.T.flatten(), SIGNAL_ORDER):
        d, v = series[s]
        u, k = units[s]
        ax.plot(d, np.array(v) / k, color=INK, lw=0.6)
        ax.set_title(f"{SIGNAL_LABEL[s]} ({u})", fontsize=7.5, loc="left")
        ax.tick_params(labelsize=7)
    for ax in axes[-1]:
        ax.set_xlim(date(2018, 1, 1), end)
    fig.tight_layout(h_pad=0.6)
    _save(fig, "fig18_signals")


def fig_capture() -> None:
    """NOAA-only capture against the EIA-implied cargo count, by year, read
    back from the generated table so the figure and the table cannot disagree."""
    txt = (HERE / "tables" / "capture.tex").read_text()
    rows = []
    for m in re.finditer(r"^\s*(\d{4}) & ([\d,]+) & ([\d,]+) & (\d+)\\%", txt, re.M):
        rows.append((int(m.group(1)), int(m.group(2).replace(",", "")), int(m.group(3).replace(",", "")), int(m.group(4))))
    years = [r[0] for r in rows]
    x = np.arange(len(years))
    fig, ax = plt.subplots(figsize=(4.6, 3.0))
    ax.bar(x - 0.2, [r[2] for r in rows], 0.4, color=GREY, label="EIA-implied cargoes")
    ax.bar(x + 0.2, [r[1] for r in rows], 0.4, color=INK, label="observed laden departures (NOAA)")
    ax2 = ax.twinx()
    ax2.plot(x, [r[3] for r in rows], color=ACCENT, marker="o", ms=3.5, lw=1.2, label="capture rate")
    ax2.axhline(100, color=ACCENT, lw=0.6, ls=":")
    ax2.set_ylim(0, 120)
    ax2.set_ylabel("capture (%)", color=ACCENT)
    ax2.grid(False)
    ax.set_xticks(x, years, fontsize=7, rotation=45)
    ax.set_ylabel("cargoes per year")
    h1, l1 = ax.get_legend_handles_labels()
    h2, l2 = ax2.get_legend_handles_labels()
    ax.legend(h1 + h2, l1 + l2, fontsize=7, loc="upper left")
    _save(fig, "fig19_capture")


LIVE_FIGURES = {
    "coverage": fig_coverage,
    "zones": fig_zones,
    "vessel": fig_vessel,
    "watchlist": fig_watchlist,
    "rescue": fig_rescue,
    "loadings": fig_loadings,
    "signals": fig_signals,
}
STATIC_FIGURES = {
    "parta": fig_parta,
    "h1": fig_h1,
    "outage": fig_outage,
    "ladder_year": fig_ladder_year,
    "year_signs": fig_year_signs,
    "mechanisms": fig_mechanisms,
    "capture": fig_capture,
}


async def main(only: list[str] | None) -> None:
    wanted = only or [*LIVE_FIGURES, *STATIC_FIGURES]
    pool = await asyncpg.create_pool(settings.database_url, min_size=1, max_size=3)
    try:
        for name in wanted:
            print(name)
            if name in LIVE_FIGURES:
                await LIVE_FIGURES[name](pool)
            else:
                STATIC_FIGURES[name]()
    finally:
        await pool.close()
    if only is None:
        # Only a full run knows every macro; a partial run must not truncate the file.
        _write_numbers()
    else:
        print(f"  (--only run: numbers2.tex left untouched; {len(NUMBERS)} macros computed)")


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description="Regenerate the second-draft figures")
    ap.add_argument("--only", nargs="+", choices=[*LIVE_FIGURES, *STATIC_FIGURES])
    _a = ap.parse_args()
    asyncio.run(main(_a.only))
